version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: cronx-redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: cronx-redis-db-network