version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cronx-postgres-db
    environment:
      - POSTGRES_DB=cronx
      - POSTGRES_USER=cronx
      - POSTGRES_PASSWORD=cronx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cronx -d cronx"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: cronx-postgres-db-network